package com.optimum.employeedashboard.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name="pool_table")
public class QuestionPool {
	
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id
	@Column(name="pool_id")
	private int poolId;
	// primary key
	// autogenerated by DB table
	@Column(name="pool_cat")
	private String poolCat;
	@Column(name="pool_type")
	private String poolType;
	@Column(name="pool_subtype")
	private String poolSubtype;
	@Column(name="no_of_qns_in_pool")
	private int noOfQnsInPool;
	@Column(name="is_hidden")
	private boolean isHidden;	
	
	
	public int getPoolId() {
		return poolId;
	}
	public void setPoolId(int poolId) {
		this.poolId = poolId;
	}
	public String getPoolCat() {
		return poolCat;
	}
	public void setPoolCat(String poolCat) {
		this.poolCat = poolCat;
	}
	public String getPoolType() {
		return poolType;
	}
	public void setPoolType(String poolType) {
		this.poolType = poolType;
	}
	public String getPoolSubtype() {
		return poolSubtype;
	}
	public void setPoolSubtype(String poolSubtype) {
		this.poolSubtype = poolSubtype;
	}
	public int getNoOfQnsInPool() {
		return noOfQnsInPool;
	}
	public void setNoOfQnsInPool(int noOfQnsInPool) {
		this.noOfQnsInPool = noOfQnsInPool;
	}
	public boolean isHidden() {
		return isHidden;
	}
	public void setHidden(boolean isHidden) {
		this.isHidden = isHidden;
	}	

	
}
