package com.optimum.employeedashboard.model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

@Entity
@Table(name="question_bank")
public class Question {

	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Id
	@Column(name="qns_id")
	private int qnsId;
	// primary key
	// auto generated by DB table
	@Column(name="pool_id")
	private int poolId;
	// foreign key
	// taken from QuestionPool
	@Column(name="qns")
	@Lob
	private byte[] questions;
	// contains URL link to uploaded question image
	@Column(name="correct_ans")
	private String correctAns;
	
	public int getQnsId() {
		return qnsId;
	}
	public void setQnsId(int qnsId) {
		this.qnsId = qnsId;
	}
	public int getPoolId() {
		return poolId;
	}
	public void setPoolId(int poolId) {
		this.poolId = poolId;
	}
	public byte[] getQns() {
		return questions;
	}
	public void setQns(byte[] qns) {
		this.questions = qns;
	}
	public String getCorrectAns() {
		return correctAns;
	}
	public void setCorrectAns(String correctAns) {
		this.correctAns = correctAns;
	}	
	
}
