package com.optimum.employeedashboard.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name="test_results")
public class TestResult {
	
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Id
	@Column(name="result_id")
	private int resultId;
	// primary key
	// auto generated by DB table
	@Column(name="settings_id")
	private int settingsId;
	// foreign key
	// taken from Test Details
	@Column(name="employee_id")
	private int employeeId;
	// nullable
	@Column(name="guest_id")
	private int guestId;
	// nullable
	
	@Column(name="user_qns_ids")
	private String userQnsIds;
	// contains concatenated string of Question Ids
	// 123,424,122,3,412
	@Column(name="user_ans")
	private String userAns;
	// contains concatenated string of chosen answers
	// B,B,C,D,C
	@Column(name="correct_ans")
	private String correctAns;
	// contains concatenated string of answer key
	// A,A,B,C,D,A
	@Column(name="score")
	private int score;
	
	public int getResultId() {
		return resultId;
	}
	public void setResultId(int resultId) {
		this.resultId = resultId;
	}
	public int getSettingsId() {
		return settingsId;
	}
	public void setSettingsId(int settingsId) {
		this.settingsId = settingsId;
	}
	public int getEmployeeId() {
		return employeeId;
	}
	public void setEmployeeId(int employeeId) {
		this.employeeId = employeeId;
	}
	public int getGuestId() {
		return guestId;
	}
	public void setGuestId(int guestId) {
		this.guestId = guestId;
	}
	public String getUserQnsIds() {
		return userQnsIds;
	}
	public void setUserQnsIds(String userQnsIds) {
		this.userQnsIds = userQnsIds;
	}
	public String getUserAns() {
		return userAns;
	}
	public void setUserAns(String userAns) {
		this.userAns = userAns;
	}
	public String getCorrectAns() {
		return correctAns;
	}
	public void setCorrectAns(String correctAns) {
		this.correctAns = correctAns;
	}
	public int getScore() {
		return score;
	}
	public void setScore(int score) {
		this.score = score;
	}	

}
